import type { AgentTarget } from '../types/config.js'

/** Partial config extracted from an agent file */
export interface ImportedConfig {
  projectName?: string
  description?: string
  language?: string
  framework?: string
  runtime?: string
  packageManager?: string
  doRules: string[]
  dontRules: string[]
  guidelines: string[]
  structure: Record<string, string>
  patterns: Record<string, string>
}

/** Abstract base class for agent file importers */
export abstract class BaseImporter {
  abstract readonly agentName: AgentTarget
  abstract readonly filePath: string
  abstract readonly displayName: string

  /** Parse agent file content into partial config */
  abstract parse(content: string): ImportedConfig

  /** Generic markdown parser for agents without a specialized importer */
  protected parseMarkdown(content: string): ImportedConfig {
    const result: ImportedConfig = {
      doRules: [],
      dontRules: [],
      guidelines: [],
      structure: {},
      patterns: {},
    }

    const lines = content.split('\n')
    let currentSection = ''

    for (const line of lines) {
      const trimmed = line.trim()

      // Skip watermark lines
      if (trimmed.startsWith('# Generated by') || trimmed.startsWith('# Source:')) continue
      if (trimmed.startsWith('# Do not edit')) continue
      if (trimmed.startsWith('# https://')) continue

      // Detect headings
      if (trimmed.startsWith('# ') && !trimmed.startsWith('## ')) {
        const title = trimmed.slice(2).trim()
        if (!result.projectName) result.projectName = title
        currentSection = 'title'
        continue
      }

      if (trimmed.startsWith('## ')) {
        currentSection = trimmed.slice(3).trim().toLowerCase()
        continue
      }

      // Parse list items based on section
      if (trimmed.startsWith('- ')) {
        const item = trimmed.slice(2).trim()
        this.parseListItem(item, currentSection, result)
      }
    }

    return result
  }

  /** Parse a list item based on the current section */
  private parseListItem(item: string, section: string, result: ImportedConfig): void {
    if (section.includes('tech stack') || section.includes('project setup')) {
      const [key, ...rest] = item.split(':')
      const value = rest.join(':').trim()
      const keyLower = key.toLowerCase().trim()
      if (keyLower.includes('language')) result.language = value
      else if (keyLower.includes('framework')) result.framework = value
      else if (keyLower.includes('runtime')) result.runtime = value
      else if (keyLower.includes('package manager')) result.packageManager = value
    } else if (section.includes('structure') || section.includes('context')) {
      const match = item.match(/^([^\s—:]+)\s*[—:]\s*(.+)$/)
      if (match) result.structure[match[1]] = match[2]
    } else if (section.includes('do not') || section.includes('never')) {
      result.dontRules.push(item)
    } else if (section === 'additional guidelines') {
      result.guidelines.push(item)
    } else if (section === 'guidelines') {
      result.doRules.push(item)
    } else if (section.includes('pattern')) {
      const match = item.match(/^\*\*([^*]+)\*\*:\s*(.+)$/)
      if (match) result.patterns[match[1]] = match[2]
      else result.guidelines.push(item)
    } else if (section.includes('instruction') || section.includes('rule')) {
      result.doRules.push(item)
    }
  }
}
