import { stringify } from 'yaml'
import type { AiCodingRulesConfig } from '../types/config.js'
import type { ScanResult } from '../types/scanner.js'
import { BaseGenerator } from './base-generator.js'

/** Additional output file info for aider */
export interface AiderOutputFile {
  path: string
  content: string
}

/** Generator for Aider (.aider.conf.yml + CONVENTIONS.md) */
export class AiderGenerator extends BaseGenerator {
  readonly agentName = 'aider' as const
  readonly outputPath = '.aider.conf.yml'
  readonly displayName = 'Aider'

  /** Store the conventions content for external retrieval */
  private conventionsContent = ''

  /** Generate .aider.conf.yml content */
  generate(config: AiCodingRulesConfig, scan: ScanResult): string {
    this.conventionsContent = this.generateConventions(config, scan)

    const pm = config.project.packageManager ?? scan.project.detectedPackageManager ?? 'npm'
    const run = pm === 'yarn' ? 'yarn' : `${pm} run`

    const yamlConfig: Record<string, unknown> = {
      'lint-cmd': `${run} lint`,
      'test-cmd': `${run} test`,
      'auto-commits': true,
      'auto-lint': true,
      read: ['CONVENTIONS.md'],
    }

    const header = [
      '# Generated by ai-coding-rules',
      '# Source: ai-coding-rules.config.json',
      "# Do not edit manually — run 'ai-coding-rules generate' to regenerate",
      '',
      `# Project: ${config.project.name}`,
      '',
    ].join('\n')

    return header + stringify(yamlConfig)
  }

  /** Get the conventions.md content (call after generate) */
  getConventionsContent(): string {
    return this.conventionsContent
  }

  /** Generate CONVENTIONS.md content */
  private generateConventions(config: AiCodingRulesConfig, scan: ScanResult): string {
    const sections: string[] = [
      this.watermark(),
      this.renderProjectOverview(config),
      this.renderTechStack(config, scan),
      this.renderCodingStandards(config),
      this.renderFileStructure(config),
      this.renderPatterns(config),
      this.renderInstructions(config),
      this.renderOverrides(config),
    ]
    return `${sections.filter((s) => s.length > 0).join('\n\n')}\n`
  }
}
