import type { AgentOverride, AgentTarget, AiCodingRulesConfig } from '../types/config.js'
import type { ScanResult } from '../types/scanner.js'

const VERSION = '0.2.0'

/** Abstract base class for all agent file generators */
export abstract class BaseGenerator {
  abstract readonly agentName: AgentTarget
  abstract readonly outputPath: string
  abstract readonly displayName: string

  /** Generate the agent-specific config file content */
  abstract generate(config: AiCodingRulesConfig, scan: ScanResult): string

  /** File header watermark */
  protected watermark(): string {
    return [
      `# Generated by rulegen v${VERSION}`,
      '# Source: rulegen.config.json',
      "# Do not edit manually — run 'rulegen generate' to regenerate",
      '# https://github.com/jhoonseo/rulegen',
      '',
    ].join('\n')
  }

  /** Render project overview section */
  protected renderProjectOverview(config: AiCodingRulesConfig): string {
    const lines: string[] = []
    lines.push(`# ${config.project.name}`)
    if (config.project.description) {
      lines.push('', config.project.description)
    }
    return lines.join('\n')
  }

  /** Render tech stack section */
  protected renderTechStack(config: AiCodingRulesConfig, scan: ScanResult): string {
    const lines: string[] = ['## Tech Stack', '']
    const info = scan.project
    lines.push(`- Language: ${config.project.language}`)
    if (config.project.framework) lines.push(`- Framework: ${config.project.framework}`)
    else if (info.detectedFramework) lines.push(`- Framework: ${info.detectedFramework}`)
    if (config.project.runtime) lines.push(`- Runtime: ${config.project.runtime}`)
    else if (info.detectedRuntime) lines.push(`- Runtime: ${info.detectedRuntime}`)
    if (config.project.packageManager)
      lines.push(`- Package Manager: ${config.project.packageManager}`)
    else if (info.detectedPackageManager)
      lines.push(`- Package Manager: ${info.detectedPackageManager}`)
    if (info.detectedTestFramework) lines.push(`- Testing: ${info.detectedTestFramework}`)
    if (info.detectedLinter) lines.push(`- Linter: ${info.detectedLinter}`)
    if (info.detectedStyleFramework) lines.push(`- Styling: ${info.detectedStyleFramework}`)
    return lines.join('\n')
  }

  /** Render coding standards section */
  protected renderCodingStandards(config: AiCodingRulesConfig): string {
    const lines: string[] = []
    const style = config.rules?.style
    const naming = config.rules?.naming

    if (style) {
      lines.push('## Code Style', '')
      if (style.indentation)
        lines.push(`- Use ${style.indentSize ?? 2} ${style.indentation} for indentation`)
      if (style.quotes) lines.push(`- ${style.quotes === 'single' ? 'Single' : 'Double'} quotes`)
      if (style.semicolons !== undefined)
        lines.push(`- ${style.semicolons ? 'Use' : 'No'} semicolons`)
      if (style.maxLineLength) lines.push(`- Max line length: ${style.maxLineLength}`)
      if (style.trailingComma) lines.push(`- Trailing commas: ${style.trailingComma}`)
    }

    if (naming) {
      lines.push('', '## Naming Conventions', '')
      if (naming.files) lines.push(`- Files: ${naming.files}`)
      if (naming.components) lines.push(`- Components: ${naming.components}`)
      if (naming.functions) lines.push(`- Functions: ${naming.functions}`)
      if (naming.constants) lines.push(`- Constants: ${naming.constants}`)
      if (naming.types) lines.push(`- Types: ${naming.types}`)
      if (naming.cssClasses) lines.push(`- CSS Classes: ${naming.cssClasses}`)
    }

    return lines.join('\n')
  }

  /** Render directory structure section */
  protected renderFileStructure(config: AiCodingRulesConfig): string {
    const entries = Object.entries(config.structure ?? {})
    if (entries.length === 0) return ''
    const lines = ['## Project Structure', '']
    for (const [dir, desc] of entries) {
      lines.push(`- ${dir} — ${desc}`)
    }
    return lines.join('\n')
  }

  /** Render do/don't instructions */
  protected renderInstructions(config: AiCodingRulesConfig): string {
    const lines: string[] = []
    const inst = config.instructions

    if (inst?.do && inst.do.length > 0) {
      lines.push('## Guidelines', '')
      for (const item of inst.do) {
        lines.push(`- ${item}`)
      }
    }

    if (inst?.dont && inst.dont.length > 0) {
      lines.push('', '## Important: Do NOT', '')
      for (const item of inst.dont) {
        lines.push(`- ${item}`)
      }
    }

    if (inst?.guidelines && inst.guidelines.length > 0) {
      lines.push('', '## Additional Guidelines', '')
      for (const item of inst.guidelines) {
        lines.push(`- ${item}`)
      }
    }

    return lines.join('\n')
  }

  /** Render key patterns section */
  protected renderPatterns(config: AiCodingRulesConfig): string {
    const patterns = config.rules?.patterns
    if (!patterns || Object.keys(patterns).length === 0) return ''
    const lines = ['## Key Patterns', '']
    for (const [key, value] of Object.entries(patterns)) {
      lines.push(`- **${key}**: ${value}`)
    }
    return lines.join('\n')
  }

  /** Get agent-specific overrides */
  protected getOverrides(config: AiCodingRulesConfig): AgentOverride | undefined {
    return config.overrides?.[this.agentName]
  }

  /** Render override extra instructions */
  protected renderOverrides(config: AiCodingRulesConfig): string {
    const overrides = this.getOverrides(config)
    if (!overrides?.extraInstructions || overrides.extraInstructions.length === 0) return ''
    const lines = ['## Additional Instructions', '']
    for (const item of overrides.extraInstructions) {
      lines.push(`- ${item}`)
    }
    return lines.join('\n')
  }

  /** Join non-empty sections with double newlines */
  protected joinSections(...sections: string[]): string {
    return sections.filter((s) => s.length > 0).join('\n\n')
  }
}
