import { stringify } from 'yaml'
import type { AiCodingRulesConfig } from '../types/config.js'
import type { ScanResult } from '../types/scanner.js'
import { BaseGenerator } from './base-generator.js'

/** Generator for Goose (.goose/config.yaml) */
export class GooseGenerator extends BaseGenerator {
  readonly agentName = 'goose' as const
  readonly outputPath = '.goose/config.yaml'
  readonly displayName = 'Goose'

  /** Generate .goose/config.yaml content */
  generate(config: AiCodingRulesConfig, scan: ScanResult): string {
    const instructions = this.buildInstructions(config, scan)
    const header = [
      '# Generated by rulegen',
      '# Source: rulegen.config.json',
      "# Do not edit manually — run 'rulegen generate' to regenerate",
      '',
    ].join('\n')
    return `${header}\n${stringify({ instructions })}`
  }

  /** Build instructions string from config */
  private buildInstructions(config: AiCodingRulesConfig, _scan: ScanResult): string {
    const lines: string[] = []

    lines.push(`Project: ${config.project.name}.`)
    if (config.project.description) lines.push(config.project.description)
    lines.push(`Language: ${config.project.language}.`)
    if (config.project.framework) lines.push(`Framework: ${config.project.framework}.`)
    if (config.project.runtime) lines.push(`Runtime: ${config.project.runtime}.`)

    const style = config.rules?.style
    if (style) {
      if (style.indentation)
        lines.push(`Use ${style.indentSize ?? 2} ${style.indentation} for indentation.`)
      if (style.quotes) lines.push(`Use ${style.quotes} quotes.`)
      if (style.semicolons !== undefined)
        lines.push(style.semicolons ? 'Use semicolons.' : 'No semicolons.')
    }

    const naming = config.rules?.naming
    if (naming) {
      if (naming.files) lines.push(`File naming: ${naming.files}.`)
      if (naming.functions) lines.push(`Function naming: ${naming.functions}.`)
      if (naming.types) lines.push(`Type naming: ${naming.types}.`)
    }

    const doRules = config.instructions?.do ?? []
    for (const rule of doRules) lines.push(rule)

    const dontRules = config.instructions?.dont ?? []
    if (dontRules.length > 0) lines.push(`Do NOT: ${dontRules.join('; ')}.`)

    const guidelines = config.instructions?.guidelines ?? []
    for (const g of guidelines) lines.push(g)

    const overrides = this.getOverrides(config)
    if (overrides?.extraInstructions) {
      for (const item of overrides.extraInstructions) lines.push(item)
    }

    return lines.join(' ')
  }
}
