import { describe, expect, it } from 'vitest'
import { ClaudeImporter } from '../../src/importers/claude-importer.js'
import { CursorImporter } from '../../src/importers/cursor-importer.js'
import { GenericImporter } from '../../src/importers/generic-importer.js'
import { mergeImports } from '../../src/importers/index.js'

const sampleClaudeMd = `# Generated by rulegen v0.1.0
# Source: rulegen.config.json
# Do not edit manually — run 'rulegen generate' to regenerate
# https://github.com/jhoonseo/rulegen

# my-app

A modern web app

## Tech Stack

- Language: typescript
- Framework: next.js
- Runtime: node
- Package Manager: pnpm

## Project Structure

- src/app — App Router pages
- src/lib — Utility functions

## Guidelines

- Use TypeScript strict mode
- Write unit tests

## Important: Do NOT

- Use 'any' type
- Use class components

## Key Patterns

- **server-components**: Use server components by default
`

const sampleCursorRules = `# Generated by rulegen v0.1.0

You are an expert typescript developer working on my-app, a modern web app.

## Code Generation Rules

When generating code, always:
- Use single quotes
- Omit semicolons

When generating code, never:
- Use 'any' type
`

describe('ClaudeImporter', () => {
  const importer = new ClaudeImporter()

  it('should parse project name from heading', () => {
    const result = importer.parse(sampleClaudeMd)
    expect(result.projectName).toBe('my-app')
  })

  it('should parse language from tech stack', () => {
    const result = importer.parse(sampleClaudeMd)
    expect(result.language).toBe('typescript')
  })

  it('should parse framework', () => {
    const result = importer.parse(sampleClaudeMd)
    expect(result.framework).toBe('next.js')
  })

  it('should parse structure', () => {
    const result = importer.parse(sampleClaudeMd)
    expect(result.structure['src/app']).toBe('App Router pages')
    expect(result.structure['src/lib']).toBe('Utility functions')
  })

  it('should parse do rules', () => {
    const result = importer.parse(sampleClaudeMd)
    expect(result.doRules).toContain('Use TypeScript strict mode')
  })

  it('should parse dont rules', () => {
    const result = importer.parse(sampleClaudeMd)
    expect(result.dontRules).toContain("Use 'any' type")
  })

  it('should parse patterns', () => {
    const result = importer.parse(sampleClaudeMd)
    expect(result.patterns['server-components']).toBe('Use server components by default')
  })
})

describe('CursorImporter', () => {
  const importer = new CursorImporter()

  it('should parse language from expert intro', () => {
    const result = importer.parse(sampleCursorRules)
    expect(result.language).toBe('typescript')
  })

  it('should parse project name from expert intro', () => {
    const result = importer.parse(sampleCursorRules)
    expect(result.projectName).toBe('my-app')
  })

  it('should parse dont rules', () => {
    const result = importer.parse(sampleCursorRules)
    expect(result.dontRules.length).toBeGreaterThan(0)
  })
})

describe('GenericImporter', () => {
  it('should parse basic markdown', () => {
    const importer = new GenericImporter('gemini', 'GEMINI.md')
    const result = importer.parse(sampleClaudeMd)
    expect(result.projectName).toBe('my-app')
    expect(result.language).toBe('typescript')
  })
})

describe('mergeImports', () => {
  it('should merge multiple imports without duplicates', () => {
    const import1 = {
      projectName: 'my-app',
      language: 'typescript',
      doRules: ['Use strict mode'],
      dontRules: ["Use 'any'"],
      guidelines: [],
      structure: { 'src/app': 'Pages' },
      patterns: {},
    }
    const import2 = {
      projectName: 'other-name',
      language: 'python',
      doRules: ['Use strict mode', 'Write tests'],
      dontRules: [],
      guidelines: ['Be concise'],
      structure: { 'src/lib': 'Utils' },
      patterns: {},
    }

    const merged = mergeImports([import1, import2])
    expect(merged.projectName).toBe('my-app') // first wins
    expect(merged.language).toBe('typescript') // first wins
    expect(merged.doRules).toEqual(['Use strict mode', 'Write tests']) // deduplicated
    expect(merged.dontRules).toEqual(["Use 'any'"])
    expect(merged.guidelines).toEqual(['Be concise'])
    expect(merged.structure).toEqual({ 'src/app': 'Pages', 'src/lib': 'Utils' })
  })

  it('should handle empty imports', () => {
    const merged = mergeImports([])
    expect(merged.doRules).toEqual([])
    expect(merged.projectName).toBeUndefined()
  })
})
