import { describe, expect, it } from 'vitest'
import { AiderGenerator } from '../../src/generators/aider-generator.js'
import { getGenerator, getGenerators } from '../../src/generators/index.js'
import type { AiCodingRulesConfig } from '../../src/types/config.js'
import type { ScanResult } from '../../src/types/scanner.js'

const mockConfig: AiCodingRulesConfig = {
  version: '1',
  project: {
    name: 'test-project',
    description: 'A test project for validation',
    type: 'web-app',
    language: 'typescript',
    framework: 'next.js',
    runtime: 'node',
    packageManager: 'pnpm',
  },
  rules: {
    style: {
      indentation: 'spaces',
      indentSize: 2,
      quotes: 'single',
      semicolons: false,
      maxLineLength: 100,
      trailingComma: 'all',
    },
    naming: {
      files: 'kebab-case',
      components: 'PascalCase',
      functions: 'camelCase',
      constants: 'UPPER_SNAKE_CASE',
      types: 'PascalCase',
    },
    patterns: {
      'server-components': 'Use server components by default',
    },
  },
  structure: {
    'src/app': 'Next.js App Router pages',
    'src/components': 'Reusable React components',
    'src/lib': 'Utility functions',
  },
  instructions: {
    do: ['Use TypeScript strict mode', 'Write unit tests for all functions'],
    dont: ["Use 'any' type", 'Use class components'],
    guidelines: ['Prefer composition over inheritance'],
  },
  targets: ['claude', 'cursor', 'copilot', 'windsurf', 'aider', 'codex'],
  overrides: {
    claude: {
      extraInstructions: ['Always run tests before committing'],
    },
  },
}

const mockScan: ScanResult = {
  project: {
    detectedLanguage: 'typescript',
    detectedFramework: 'next.js',
    detectedRuntime: 'node',
    detectedPackageManager: 'pnpm',
    detectedTestFramework: 'vitest',
    detectedLinter: 'biome',
    detectedFormatter: 'biome',
    detectedStyleFramework: 'tailwind',
  },
  structure: {
    rootFiles: ['package.json', 'tsconfig.json'],
    directories: ['src', 'tests'],
    entryPoints: ['src/index.ts'],
    configFiles: ['tsconfig.json', 'biome.json'],
    totalFileCount: 50,
  },
  git: {
    isGitRepo: true,
    defaultBranch: 'main',
    hasGitignore: true,
    usesConventionalCommits: true,
    hasCI: true,
    ciPlatform: 'github-actions',
  },
  dependencies: {
    raw: { react: '^18', vitest: '^1', tsup: '^8' },
    categorized: {
      ui: ['react'],
      state: [],
      styling: [],
      api: [],
      database: [],
      testing: ['vitest'],
      build: ['tsup'],
      other: [],
    },
  },
}

describe('ClaudeGenerator', () => {
  const gen = getGenerator('claude')

  it('should generate CLAUDE.md with watermark', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Generated by rulegen')
  })

  it('should have build commands at the top', () => {
    const output = gen.generate(mockConfig, mockScan)
    const overviewIdx = output.indexOf('# test-project')
    const buildIdx = output.indexOf('## Build & Test Commands')
    const techIdx = output.indexOf('## Tech Stack')
    expect(buildIdx).toBeGreaterThan(overviewIdx)
    expect(buildIdx).toBeLessThan(techIdx)
  })

  it('should include pnpm commands', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('pnpm run build')
    expect(output).toContain('pnpm run test')
  })

  it('should include overrides for claude', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Always run tests before committing')
  })

  it('should output to CLAUDE.md', () => {
    expect(gen.outputPath).toBe('CLAUDE.md')
  })
})

describe('CursorGenerator', () => {
  const gen = getGenerator('cursor')

  it('should start with "You are an expert"', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('You are an expert typescript developer')
  })

  it('should include "When generating code, always/never" pattern', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('When generating code, always:')
    expect(output).toContain('When generating code, never:')
  })

  it('should include watermark', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Generated by rulegen')
  })

  it('should output to .cursorrules', () => {
    expect(gen.outputPath).toBe('.cursorrules')
  })
})

describe('CopilotGenerator', () => {
  const gen = getGenerator('copilot')

  it('should include General Guidelines', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('## General Guidelines')
  })

  it('should include code examples', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('### Preferred Pattern')
    expect(output).toContain('### Avoid')
  })

  it('should output to .github/copilot-instructions.md', () => {
    expect(gen.outputPath).toBe('.github/copilot-instructions.md')
  })
})

describe('WindsurfGenerator', () => {
  const gen = getGenerator('windsurf')

  it('should include Rules section', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('## Rules')
  })

  it('should include watermark', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Generated by rulegen')
  })

  it('should output to .windsurfrules', () => {
    expect(gen.outputPath).toBe('.windsurfrules')
  })
})

describe('AiderGenerator', () => {
  it('should generate valid YAML', () => {
    const gen = getGenerator('aider') as AiderGenerator
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('lint-cmd:')
    expect(output).toContain('test-cmd:')
    expect(output).toContain('auto-commits:')
    expect(output).toContain('CONVENTIONS.md')
  })

  it('should generate conventions content', () => {
    const gen = new AiderGenerator()
    gen.generate(mockConfig, mockScan)
    const conventions = gen.getConventionsContent()
    expect(conventions).toContain('test-project')
    expect(conventions).toContain('Generated by rulegen')
  })

  it('should output to .aider.conf.yml', () => {
    expect(getGenerator('aider').outputPath).toBe('.aider.conf.yml')
  })
})

describe('CodexGenerator', () => {
  const gen = getGenerator('codex')

  it('should have Instructions section at top', () => {
    const output = gen.generate(mockConfig, mockScan)
    const instructionsIdx = output.indexOf('## Instructions')
    const setupIdx = output.indexOf('## Project Setup')
    expect(instructionsIdx).toBeLessThan(setupIdx)
  })

  it('should include "You are working on" line', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('You are working on test-project')
  })

  it('should output to codex.md', () => {
    expect(gen.outputPath).toBe('codex.md')
  })
})

describe('getGenerators', () => {
  it('should return all 6 generators', () => {
    const all = getGenerators(['claude', 'cursor', 'copilot', 'windsurf', 'aider', 'codex'])
    expect(all).toHaveLength(6)
  })

  it('should return subset of generators', () => {
    const subset = getGenerators(['claude', 'cursor'])
    expect(subset).toHaveLength(2)
  })
})

describe('empty instructions', () => {
  it('should not error with empty instructions', () => {
    const emptyConfig: AiCodingRulesConfig = {
      version: '1',
      project: {
        name: 'empty',
        type: 'library',
        language: 'typescript',
      },
      rules: {},
      structure: {},
      instructions: {},
      targets: ['claude'],
    }
    const gen = getGenerator('claude')
    expect(() => gen.generate(emptyConfig, mockScan)).not.toThrow()
  })
})
