import { describe, expect, it } from 'vitest'
import { getGenerator, getGenerators } from '../../src/generators/index.js'
import type { AiCodingRulesConfig } from '../../src/types/config.js'
import type { ScanResult } from '../../src/types/scanner.js'

const mockConfig: AiCodingRulesConfig = {
  version: '1',
  project: {
    name: 'test-project',
    description: 'A test project',
    type: 'web-app',
    language: 'typescript',
    framework: 'next.js',
    runtime: 'node',
    packageManager: 'pnpm',
  },
  rules: {
    style: {
      indentation: 'spaces',
      indentSize: 2,
      quotes: 'single',
      semicolons: false,
    },
    naming: {
      files: 'kebab-case',
      functions: 'camelCase',
      types: 'PascalCase',
    },
    patterns: {
      'server-components': 'Use server components by default',
    },
  },
  structure: {
    'src/app': 'App Router pages',
    'src/components': 'Reusable components',
  },
  instructions: {
    do: ['Use TypeScript strict mode'],
    dont: ["Use 'any' type"],
    guidelines: ['Prefer composition over inheritance'],
  },
  targets: ['claude'],
}

const mockScan: ScanResult = {
  project: {
    detectedLanguage: 'typescript',
    detectedFramework: 'next.js',
    detectedRuntime: 'node',
    detectedPackageManager: 'pnpm',
    detectedTestFramework: 'vitest',
    detectedLinter: 'biome',
    detectedFormatter: 'biome',
    detectedStyleFramework: null,
  },
  structure: {
    rootFiles: ['package.json'],
    directories: ['src'],
    entryPoints: ['src/index.ts'],
    configFiles: ['tsconfig.json'],
    totalFileCount: 20,
  },
  git: {
    isGitRepo: true,
    defaultBranch: 'main',
    hasGitignore: true,
    usesConventionalCommits: false,
    hasCI: false,
    ciPlatform: null,
  },
  dependencies: {
    raw: {},
    categorized: {
      ui: [],
      state: [],
      styling: [],
      api: [],
      database: [],
      testing: [],
      build: [],
      other: [],
    },
  },
}

describe('GeminiGenerator', () => {
  const gen = getGenerator('gemini')

  it('should output to GEMINI.md', () => {
    expect(gen.outputPath).toBe('GEMINI.md')
  })

  it('should include watermark', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Generated by rulegen')
  })

  it('should include project name', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('test-project')
  })
})

describe('ClineGenerator', () => {
  const gen = getGenerator('cline')

  it('should output to .clinerules/project.md', () => {
    expect(gen.outputPath).toBe('.clinerules/project.md')
  })

  it('should include watermark', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Generated by rulegen')
  })

  it('should include tech stack', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('typescript')
  })
})

describe('OpenCodeGenerator', () => {
  const gen = getGenerator('opencode')

  it('should output to .opencode/rules.md', () => {
    expect(gen.outputPath).toBe('.opencode/rules.md')
  })

  it('should include instructions', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('TypeScript strict mode')
  })
})

describe('RooCodeGenerator', () => {
  const gen = getGenerator('roocode')

  it('should output to .roo/rules.md', () => {
    expect(gen.outputPath).toBe('.roo/rules.md')
  })

  it('should include structure', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('src/app')
  })
})

describe('JunieGenerator', () => {
  const gen = getGenerator('junie')

  it('should output to .junie/guidelines.md', () => {
    expect(gen.outputPath).toBe('.junie/guidelines.md')
  })

  it('should include patterns', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('server-components')
  })
})

describe('ContinueGenerator', () => {
  const gen = getGenerator('continue')

  it('should output to .continue/rules.md', () => {
    expect(gen.outputPath).toBe('.continue/rules.md')
  })

  it('should include dont rules', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain("Use 'any' type")
  })
})

describe('CodyGenerator', () => {
  const gen = getGenerator('cody')

  it('should output to .vscode/cody.json', () => {
    expect(gen.outputPath).toBe('.vscode/cody.json')
  })

  it('should generate valid JSON with instructions field', () => {
    const output = gen.generate(mockConfig, mockScan)
    const parsed = JSON.parse(output)
    expect(parsed).toHaveProperty('instructions')
    expect(typeof parsed.instructions).toBe('string')
  })

  it('should include project info in instructions', () => {
    const output = gen.generate(mockConfig, mockScan)
    const parsed = JSON.parse(output)
    expect(parsed.instructions).toContain('test-project')
    expect(parsed.instructions).toContain('typescript')
  })
})

describe('AgentsGenerator', () => {
  const gen = getGenerator('agents')

  it('should output to AGENTS.md', () => {
    expect(gen.outputPath).toBe('AGENTS.md')
  })

  it('should include watermark', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Generated by rulegen')
  })
})

describe('GooseGenerator', () => {
  const gen = getGenerator('goose')

  it('should output to .goose/config.yaml', () => {
    expect(gen.outputPath).toBe('.goose/config.yaml')
  })

  it('should generate YAML with instructions field', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('instructions:')
  })

  it('should include project info', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('test-project')
  })
})

describe('AmpGenerator', () => {
  const gen = getGenerator('amp')

  it('should output to .amp/rules.md', () => {
    expect(gen.outputPath).toBe('.amp/rules.md')
  })

  it('should include guidelines', () => {
    const output = gen.generate(mockConfig, mockScan)
    expect(output).toContain('Prefer composition over inheritance')
  })
})

describe('getGenerators with all 16', () => {
  it('should return all 16 generators', () => {
    const all = getGenerators([
      'claude',
      'cursor',
      'copilot',
      'windsurf',
      'aider',
      'codex',
      'gemini',
      'cline',
      'opencode',
      'roocode',
      'junie',
      'continue',
      'cody',
      'agents',
      'goose',
      'amp',
    ])
    expect(all).toHaveLength(16)
  })
})
